#!/bin/sh

# Check if Waybar is already running

if pgrep -x "waybar" > /dev/null
then
    # Waybar is already running, so kill it
    killall waybar
fi
# Start Waybar with the specified configuration and style files
waybar --log-level=debug -c $HOME/.config/hypr/component/waybar/config -s $HOME/.config/hypr/component/waybar/style.css &
